name: untitled2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dotted_line: ^3.2.2
  flutter_svg: ^2.0.10+1
  intl: any
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3
  diacritic: ^0.1.5
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^14.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/book_entry_form_ticket.png
    - assets/images/book_sale_invoice_ticket.png
    - assets/icons/new_to_old_1.svg
    - assets/icons/new_to_old_2.svg
    - assets/icons/old_to_new_1.svg
    - assets/icons/old_to_new_2.svg
  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-Thin.ttf
          weight: 100
        - asset: assets/fonts/Archivo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Archivo-Light.ttf
          weight: 300
        - asset: assets/fonts/Archivo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Archivo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Archivo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Archivo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Archivo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Archivo-Black.ttf
          weight: 900