// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx2y_tE8afWirhjEQubyQzQWV9U-xkYYY',
    appId: '1:762126839247:web:aacc5a7237b5292a7fb6ba',
    messagingSenderId: '762126839247',
    projectId: 'bookstore-management-sys-614c4',
    authDomain: 'bookstore-management-sys-614c4.firebaseapp.com',
    storageBucket: 'bookstore-management-sys-614c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCxbC7TRDtAONm8Odhs-hjDSzZsmRGzQY',
    appId: '1:762126839247:android:e3001a3a8dfd5ce17fb6ba',
    messagingSenderId: '762126839247',
    projectId: 'bookstore-management-sys-614c4',
    storageBucket: 'bookstore-management-sys-614c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAid_rqSafHUwRJZFpbDaV9d9vjtVmAfRU',
    appId: '1:762126839247:ios:2742993f937b50d27fb6ba',
    messagingSenderId: '762126839247',
    projectId: 'bookstore-management-sys-614c4',
    storageBucket: 'bookstore-management-sys-614c4.appspot.com',
    iosBundleId: 'com.example.bookstoreManagementSystem',
  );
}
